# Generated by Django 4.0.2 on 2022-02-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='after',
            new_name='muallif',
        ),
    ]
